/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryPaperIdRouteImport } from './routes/library_.$paperId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryPaperIdRoute = LibraryPaperIdRouteImport.update({
  id: '/library_/$paperId',
  path: '/library/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/library': typeof LibraryRoute
  '/manager': typeof ManagerRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
  '/library/$paperId': typeof LibraryPaperIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/library': typeof LibraryRoute
  '/manager': typeof ManagerRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
  '/library/$paperId': typeof LibraryPaperIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/library': typeof LibraryRoute
  '/manager': typeof ManagerRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
  '/library_/$paperId': typeof LibraryPaperIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/library'
    | '/manager'
    | '/research'
    | '/search'
    | '/settings'
    | '/workspace'
    | '/library/$paperId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/library'
    | '/manager'
    | '/research'
    | '/search'
    | '/settings'
    | '/workspace'
    | '/library/$paperId'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/library'
    | '/manager'
    | '/research'
    | '/search'
    | '/settings'
    | '/workspace'
    | '/library_/$paperId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  LibraryRoute: typeof LibraryRoute
  ManagerRoute: typeof ManagerRoute
  ResearchRoute: typeof ResearchRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  LibraryPaperIdRoute: typeof LibraryPaperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library_/$paperId': {
      id: '/library_/$paperId'
      path: '/library/$paperId'
      fullPath: '/library/$paperId'
      preLoaderRoute: typeof LibraryPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  LibraryRoute: LibraryRoute,
  ManagerRoute: ManagerRoute,
  ResearchRoute: ResearchRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceRoute: WorkspaceRoute,
  LibraryPaperIdRoute: LibraryPaperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
